### ISSUE TITLE
链接postgresql启动报错

### ISSUE THREAD

**Issue by xuniyuqi** [zhudyos/duic#23]
java -Dspring.profiles.active=postgresql -jar duic-2.3.2-beta.jar 
 ______              _    ______
|_   _ `.           (_) .' ___  |
  | | `. \ __   _   __ / .'   \_|
  | |  | |[  | | | [  || |
 _| |_.' / | \_/ |, | |\ `.___.'\
|______.'  '.__.'_/[___]`.____ .'
:: duic ::          (v2.3.2-beta)

2019-02-02 22:01:47,049 INFO  i.z.d.server.Application$Companion - Starting Application.Companion v2.3.2-beta on ubuntu with PID 16816 (/home/bill/Downloads/duic-2.3.2-beta.jar started by bill in /home/bill/Downloads)
2019-02-02 22:01:47,051 INFO  i.z.d.server.Application$Companion - The following profiles are active: postgresql
2019-02-02 22:01:48,588 INFO  o.s.c.a.ConfigurationClassEnhancer - @Bean method Application.kotlinPropertyConfigurer is non-static and returns an object assignable to Spring's BeanFactoryPostProcessor interface. This will result in a failure to process annotations such as @Autowired, @Resource and @PostConstruct within the method's declaring @Configuration class. Add the 'static' modifier to this method to avoid these container lifecycle issues; see @Bean javadoc for complete details.
2019-02-02 22:01:49,695 INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2019-02-02 22:01:50,279 INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2019-02-02 22:01:55,034 INFO  o.s.s.c.ThreadPoolTaskScheduler - Initializing ExecutorService 'taskScheduler'
2019-02-02 22:01:55,379 INFO  o.s.b.w.e.netty.NettyWebServer - Netty started on port(s): 7777
2019-02-02 22:01:55,391 INFO  i.z.d.server.Application$Companion - Started Application.Companion in 9.799 seconds (JVM running for 10.636)
2019-02-02 22:01:55,581 ERROR reactor.core.scheduler.Schedulers - Scheduler worker in group main failed with an uncaught exception
reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [SELECT VERSION() AS 'version']; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at or near "'version'"
  Position: 21
Caused by: org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [SELECT VERSION() AS 'version']; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at or near "'version'"
  Position: 21
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:234)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1444)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:632)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:694)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:748)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:235)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:244)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForMap(NamedParameterJdbcTemplate.java:272)
	at io.zhudy.duic.repository.impl.PostgreSQLServerRepository$findDbVersion$1$v$1.doInTransaction(PostgreSQLServerRepository.kt:112)
	at io.zhudy.duic.repository.impl.PostgreSQLServerRepository$findDbVersion$1$v$1.doInTransaction(PostgreSQLServerRepository.kt:34)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at io.zhudy.duic.repository.impl.PostgreSQLServerRepository$findDbVersion$1.accept(PostgreSQLServerRepository.kt:111)
	at io.zhudy.duic.repository.impl.PostgreSQLServerRepository$findDbVersion$1.accept(PostgreSQLServerRepository.kt:34)
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:53)
	at reactor.core.publisher.MonoOnAssembly.subscribe(MonoOnAssembly.java:61)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3695)
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:123)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoCreate] :
	reactor.core.publisher.Mono.create(Mono.java:183)
	io.zhudy.duic.repository.impl.PostgreSQLServerRepository.findDbVersion(PostgreSQLServerRepository.kt:110)
Error has been observed by the following operator(s):
	|_	Mono.create ⇢ io.zhudy.duic.repository.impl.PostgreSQLServerRepository.findDbVersion(PostgreSQLServerRepository.kt:110)
	|_	Mono.subscribeOn ⇢ io.zhudy.duic.repository.impl.PostgreSQLServerRepository.findDbVersion(PostgreSQLServerRepository.kt:116)

Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "'version'"
  Position: 21
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:678)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
	... 22 common frames omitted
2019-02-02 22:01:58,398 INFO  o.s.s.c.ThreadPoolTaskScheduler - Shutting down ExecutorService 'taskScheduler'
2019-02-02 22:01:58,402 INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2019-02-02 22:01:58,431 ERROR io.zhudy.duic.service.ServerService - unregister 服务失败: ubuntu:7777
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is java.lang.NullPointerException
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:305)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:378)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:137)
	at io.zhudy.duic.repository.impl.PostgreSQLServerRepository$register$1.accept(PostgreSQLServerRepository.kt:41)
	at io.zhudy.duic.repository.impl.PostgreSQLServerRepository$register$1.accept(PostgreSQLServerRepository.kt:34)
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:53)
	at reactor.core.publisher.MonoOnAssembly.subscribe(MonoOnAssembly.java:61)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3695)
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:123)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoCreate] :
	reactor.core.publisher.Mono.create(Mono.java:183)
	io.zhudy.duic.repository.impl.PostgreSQLServerRepository.register(PostgreSQLServerRepository.kt:40)
Error has been observed by the following operator(s):
	|_	Mono.create ⇢ io.zhudy.duic.repository.impl.PostgreSQLServerRepository.register(PostgreSQLServerRepository.kt:40)
	|_	Mono.subscribeOn ⇢ io.zhudy.duic.repository.impl.PostgreSQLServerRepository.register(PostgreSQLServerRepository.kt:52)

Caused by: java.lang.NullPointerException: null
	at com.zaxxer.hikari.pool.HikariProxyConnection.getAutoCommit(HikariProxyConnection.java)
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:278)
	... 15 common frames omitted
2019-02-02 22:01:58,440 INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.

**Comment by kevin70** [comment]
你使用的 `postgresql` 版本是多少？
